#!/usr/bin/env bash
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
template_dir="$here/template"
result_dir="$here/result"
config="$here/mountpoints.json"

for cmd in jq envsubst systemd-escape; do
  command -v "$cmd" >/dev/null || {
    echo "error: required command not found: $cmd" >&2
    exit 1
  }
done

[[ -f $config ]] || {
  echo "error: $config not found; copy mountpoints.example.json and edit it" >&2
  exit 1
}

# XDG_DATA_HOME may be referenced from mountpoints.json but unset in the caller env.
: "${XDG_DATA_HOME:=$HOME/.local/share}"
export XDG_DATA_HOME

# Export each .env entry as-is (keys must be UPPER_SNAKE_CASE identifiers)
# and collect the names so envsubst only touches variables we defined.
template_vars=""
while IFS=$'\t' read -r key value; do
  [[ $key =~ ^[A-Z_][A-Z0-9_]*$ ]] || {
    echo "error: env key is not UPPER_SNAKE_CASE: $key" >&2
    exit 1
  }
  export "$key=$value"
  template_vars+=" \${$key}"
done < <(jq -r '.env | to_entries[] | [.key, .value] | @tsv' "$config")

export DISK_SYSTEMD_DEVICE_UNIT_NAME="$(systemd-escape --path "/dev/disk/by-label/$DISK_LABEL").device"
template_vars+=' ${DISK_SYSTEMD_DEVICE_UNIT_NAME}'
template_vars+=' ${SNAPSHOT_SCRIPT}'
# install location of the per-subvolume snapshot scripts; ExecStart= references
# it directly, generate-snapshot-scripts.sh stages them under result/
snapshot_script_dir="${SNAPSHOT_SCRIPT_DIR:-/usr/local/libexec/btrfs-snapshot}"
[[ $snapshot_script_dir = /* ]] || {
  echo "error: SNAPSHOT_SCRIPT_DIR must be an absolute path: $snapshot_script_dir" >&2
  exit 1
}
template_vars+=' ${SUBVOL_NAME} ${SUBVOL_PATH} ${SUBVOL_MOUNT_PATH} ${SUBVOL_COMPRESSION}'
template_vars+=' ${SNAPSHOT_INTERVAL}'
# spreads snapshot timer firings, notably the Persistent catch-up burst at boot
: "${SNAPSHOT_RANDOMIZED_DELAY:=10min}"
export SNAPSHOT_RANDOMIZED_DELAY
template_vars+=' ${SNAPSHOT_RANDOMIZED_DELAY}'

render() {
  local tmpl=$1 out=$2
  envsubst "$template_vars" <"$tmpl" >"$out"
  echo "generated ${out#"$here/"}"
}

while IFS= read -r -d '' tmpl; do
  rel="${tmpl#"$template_dir/"}"
  out_dir="$result_dir/$(dirname "$rel")"
  mkdir -p "$out_dir"
  case "$(basename "$tmpl")" in
    root.mount.template)
      render "$tmpl" "$out_dir/$(systemd-escape --path "$ROOT_POOL").mount"
      ;;
    subvolume.mount.template)
      while IFS= read -r entry; do
        # volname / mount-to may reference caller env like ${USER}, ${HOME}, ${XDG_DATA_HOME}.
        SUBVOL_PATH="$(jq -r '.volname' <<<"$entry" | envsubst)"
        SUBVOL_MOUNT_PATH="$(jq -r '."mount-to"' <<<"$entry" | envsubst)"
        SUBVOL_NAME="$SUBVOL_PATH"
        SUBVOL_COMPRESSION="$FS_COMPRESSION"
        export SUBVOL_NAME SUBVOL_PATH SUBVOL_MOUNT_PATH SUBVOL_COMPRESSION
        render "$tmpl" "$out_dir/$(systemd-escape --path "$SUBVOL_MOUNT_PATH").mount"
      done < <(jq -c '.subvolume[]' "$config")
      ;;
    snapshot.service.template | snapshot.timer.template)
      kind="$(basename "$tmpl" .template)"
      kind="${kind#snapshot.}"
      while IFS= read -r entry; do
        SUBVOL_NAME="$(jq -r '.volname' <<<"$entry" | envsubst)"
        mount_to="$(jq -r '."mount-to"' <<<"$entry" | envsubst)"
        esc="$(systemd-escape --path "$mount_to")"
        # per-subvolume script generated by generate-snapshot-scripts.sh
        SNAPSHOT_SCRIPT="$snapshot_script_dir/$esc.sh"
        export SUBVOL_NAME SNAPSHOT_SCRIPT
        while IFS= read -r interval; do
          export SNAPSHOT_INTERVAL="$interval"
          render "$tmpl" "$out_dir/btrfs-snapshot-$esc-$interval.$kind"
        done < <(jq -r '.snapshot[].interval' <<<"$entry")
      done < <(jq -c '.subvolume[] | select(.snapshot)' "$config")
      ;;
    *.template)
      render "$tmpl" "$out_dir/$(basename "$tmpl" .template)"
      ;;
    *)
      render "$tmpl" "$out_dir/$(basename "$tmpl")"
      ;;
  esac
done < <(find "$template_dir" -type f -print0)
