name: bastion-chrome
work_dir: $HOME

commands:
  unlock:
    args:
      - $HOME/.nix-profile/bin/zsh
      - -lic
      - ssh-add -T "${SSH_PUBKEY}"
    env:
      - SSH_PUBKEY=${SSH_PUBKEY:-$HOME/.ssh/id_ecdsa.pub}
    tty: true
  proxy:
    args:
      - $HOME/.nix-profile/bin/zsh
      - -lc
      - ssh -ND 1090 "${SSH_BASTION}"
    env:
      - SSH_BASTION=${SSH_BASTION:-bastion}
    after:
      unlock:
        condition: completed_successfully
  chrome:
    args:
      - $HOME/.nix-profile/bin/zsh
      - -lc
      - google-chrome --proxy-server="socks5://localhost:1090"
    after:
      proxy:
        condition: running
mux:
  layouts:
    - name: default
      root:
        dir: v
        splits: [50%, 50%]
        panes:
          - command: unlock
            focus: true
          - command: proxy
