PODMAN=${XDG_DATA_HOME:-$HOME/.local/share}/containers/bin/podman
PATH=/home/watage/.local/containers/libexec/podman:/home/watage/.local/containers/lib/podman:/home/watage/.local/containers/bin:${PATH}
