// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/lspgw.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LspGateway_GetDefinition_FullMethodName      = "/lspgw.LspGateway/GetDefinition"
	LspGateway_GetReferences_FullMethodName      = "/lspgw.LspGateway/GetReferences"
	LspGateway_GetHover_FullMethodName           = "/lspgw.LspGateway/GetHover"
	LspGateway_GetDocumentSymbols_FullMethodName = "/lspgw.LspGateway/GetDocumentSymbols"
	LspGateway_GetDiagnostics_FullMethodName     = "/lspgw.LspGateway/GetDiagnostics"
	LspGateway_Health_FullMethodName             = "/lspgw.LspGateway/Health"
	LspGateway_DaemonStatus_FullMethodName       = "/lspgw.LspGateway/DaemonStatus"
	LspGateway_Shutdown_FullMethodName           = "/lspgw.LspGateway/Shutdown"
)

// LspGatewayClient is the client API for LspGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LspGatewayClient interface {
	GetDefinition(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	GetReferences(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	GetHover(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	GetDocumentSymbols(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	GetDiagnostics(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Health(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	DaemonStatus(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type lspGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewLspGatewayClient(cc grpc.ClientConnInterface) LspGatewayClient {
	return &lspGatewayClient{cc}
}

func (c *lspGatewayClient) GetDefinition(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_GetDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspGatewayClient) GetReferences(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_GetReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspGatewayClient) GetHover(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_GetHover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspGatewayClient) GetDocumentSymbols(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_GetDocumentSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspGatewayClient) GetDiagnostics(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_GetDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspGatewayClient) Health(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspGatewayClient) DaemonStatus(ctx context.Context, in *DaemonStatusRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_DaemonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lspGatewayClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LspGateway_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LspGatewayServer is the server API for LspGateway service.
// All implementations must embed UnimplementedLspGatewayServer
// for forward compatibility.
type LspGatewayServer interface {
	GetDefinition(context.Context, *LocationRequest) (*QueryResponse, error)
	GetReferences(context.Context, *LocationRequest) (*QueryResponse, error)
	GetHover(context.Context, *LocationRequest) (*QueryResponse, error)
	GetDocumentSymbols(context.Context, *FileRequest) (*QueryResponse, error)
	GetDiagnostics(context.Context, *FileRequest) (*QueryResponse, error)
	Health(context.Context, *ProjectRequest) (*QueryResponse, error)
	DaemonStatus(context.Context, *DaemonStatusRequest) (*QueryResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*QueryResponse, error)
	mustEmbedUnimplementedLspGatewayServer()
}

// UnimplementedLspGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLspGatewayServer struct{}

func (UnimplementedLspGatewayServer) GetDefinition(context.Context, *LocationRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefinition not implemented")
}
func (UnimplementedLspGatewayServer) GetReferences(context.Context, *LocationRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReferences not implemented")
}
func (UnimplementedLspGatewayServer) GetHover(context.Context, *LocationRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHover not implemented")
}
func (UnimplementedLspGatewayServer) GetDocumentSymbols(context.Context, *FileRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentSymbols not implemented")
}
func (UnimplementedLspGatewayServer) GetDiagnostics(context.Context, *FileRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedLspGatewayServer) Health(context.Context, *ProjectRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLspGatewayServer) DaemonStatus(context.Context, *DaemonStatusRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DaemonStatus not implemented")
}
func (UnimplementedLspGatewayServer) Shutdown(context.Context, *ShutdownRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedLspGatewayServer) mustEmbedUnimplementedLspGatewayServer() {}
func (UnimplementedLspGatewayServer) testEmbeddedByValue()                    {}

// UnsafeLspGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LspGatewayServer will
// result in compilation errors.
type UnsafeLspGatewayServer interface {
	mustEmbedUnimplementedLspGatewayServer()
}

func RegisterLspGatewayServer(s grpc.ServiceRegistrar, srv LspGatewayServer) {
	// If the following call pancis, it indicates UnimplementedLspGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LspGateway_ServiceDesc, srv)
}

func _LspGateway_GetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).GetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_GetDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).GetDefinition(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspGateway_GetReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).GetReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_GetReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).GetReferences(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspGateway_GetHover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).GetHover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_GetHover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).GetHover(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspGateway_GetDocumentSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).GetDocumentSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_GetDocumentSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).GetDocumentSymbols(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspGateway_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_GetDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).GetDiagnostics(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspGateway_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).Health(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspGateway_DaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).DaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_DaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).DaemonStatus(ctx, req.(*DaemonStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LspGateway_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LspGatewayServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LspGateway_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LspGatewayServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LspGateway_ServiceDesc is the grpc.ServiceDesc for LspGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LspGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lspgw.LspGateway",
	HandlerType: (*LspGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDefinition",
			Handler:    _LspGateway_GetDefinition_Handler,
		},
		{
			MethodName: "GetReferences",
			Handler:    _LspGateway_GetReferences_Handler,
		},
		{
			MethodName: "GetHover",
			Handler:    _LspGateway_GetHover_Handler,
		},
		{
			MethodName: "GetDocumentSymbols",
			Handler:    _LspGateway_GetDocumentSymbols_Handler,
		},
		{
			MethodName: "GetDiagnostics",
			Handler:    _LspGateway_GetDiagnostics_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LspGateway_Health_Handler,
		},
		{
			MethodName: "DaemonStatus",
			Handler:    _LspGateway_DaemonStatus_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _LspGateway_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lspgw.proto",
}
