// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: proto/lspgw.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Filepath      string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Col           int32                  `protobuf:"varint,4,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationRequest) Reset() {
	*x = LocationRequest{}
	mi := &file_proto_lspgw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequest) ProtoMessage() {}

func (x *LocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lspgw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequest.ProtoReflect.Descriptor instead.
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_lspgw_proto_rawDescGZIP(), []int{0}
}

func (x *LocationRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *LocationRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *LocationRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LocationRequest) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Filepath      string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_lspgw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lspgw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_lspgw_proto_rawDescGZIP(), []int{1}
}

func (x *FileRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *FileRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type ProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	mi := &file_proto_lspgw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lspgw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_lspgw_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type DaemonStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonStatusRequest) Reset() {
	*x = DaemonStatusRequest{}
	mi := &file_proto_lspgw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatusRequest) ProtoMessage() {}

func (x *DaemonStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lspgw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatusRequest.ProtoReflect.Descriptor instead.
func (*DaemonStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_lspgw_proto_rawDescGZIP(), []int{3}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_lspgw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lspgw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_lspgw_proto_rawDescGZIP(), []int{4}
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result        *structpb.Value        `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_lspgw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lspgw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_lspgw_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_lspgw_proto protoreflect.FileDescriptor

const file_proto_lspgw_proto_rawDesc = "" +
	"\n" +
	"\x11proto/lspgw.proto\x12\x05lspgw\x1a\x1cgoogle/protobuf/struct.proto\"m\n" +
	"\x0fLocationRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x10\n" +
	"\x03col\x18\x04 \x01(\x05R\x03col\"C\n" +
	"\vFileRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\"*\n" +
	"\x0eProjectRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\x15\n" +
	"\x13DaemonStatusRequest\"\x11\n" +
	"\x0fShutdownRequest\"e\n" +
	"\rQueryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x06result\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x06result2\xf3\x03\n" +
	"\n" +
	"LspGateway\x12=\n" +
	"\rGetDefinition\x12\x16.lspgw.LocationRequest\x1a\x14.lspgw.QueryResponse\x12=\n" +
	"\rGetReferences\x12\x16.lspgw.LocationRequest\x1a\x14.lspgw.QueryResponse\x128\n" +
	"\bGetHover\x12\x16.lspgw.LocationRequest\x1a\x14.lspgw.QueryResponse\x12>\n" +
	"\x12GetDocumentSymbols\x12\x12.lspgw.FileRequest\x1a\x14.lspgw.QueryResponse\x12:\n" +
	"\x0eGetDiagnostics\x12\x12.lspgw.FileRequest\x1a\x14.lspgw.QueryResponse\x125\n" +
	"\x06Health\x12\x15.lspgw.ProjectRequest\x1a\x14.lspgw.QueryResponse\x12@\n" +
	"\fDaemonStatus\x12\x1a.lspgw.DaemonStatusRequest\x1a\x14.lspgw.QueryResponse\x128\n" +
	"\bShutdown\x12\x16.lspgw.ShutdownRequest\x1a\x14.lspgw.QueryResponseB Z\x1egithub.com/watage/lsp-gw/protob\x06proto3"

var (
	file_proto_lspgw_proto_rawDescOnce sync.Once
	file_proto_lspgw_proto_rawDescData []byte
)

func file_proto_lspgw_proto_rawDescGZIP() []byte {
	file_proto_lspgw_proto_rawDescOnce.Do(func() {
		file_proto_lspgw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lspgw_proto_rawDesc), len(file_proto_lspgw_proto_rawDesc)))
	})
	return file_proto_lspgw_proto_rawDescData
}

var file_proto_lspgw_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_lspgw_proto_goTypes = []any{
	(*LocationRequest)(nil),     // 0: lspgw.LocationRequest
	(*FileRequest)(nil),         // 1: lspgw.FileRequest
	(*ProjectRequest)(nil),      // 2: lspgw.ProjectRequest
	(*DaemonStatusRequest)(nil), // 3: lspgw.DaemonStatusRequest
	(*ShutdownRequest)(nil),     // 4: lspgw.ShutdownRequest
	(*QueryResponse)(nil),       // 5: lspgw.QueryResponse
	(*structpb.Value)(nil),      // 6: google.protobuf.Value
}
var file_proto_lspgw_proto_depIdxs = []int32{
	6, // 0: lspgw.QueryResponse.result:type_name -> google.protobuf.Value
	0, // 1: lspgw.LspGateway.GetDefinition:input_type -> lspgw.LocationRequest
	0, // 2: lspgw.LspGateway.GetReferences:input_type -> lspgw.LocationRequest
	0, // 3: lspgw.LspGateway.GetHover:input_type -> lspgw.LocationRequest
	1, // 4: lspgw.LspGateway.GetDocumentSymbols:input_type -> lspgw.FileRequest
	1, // 5: lspgw.LspGateway.GetDiagnostics:input_type -> lspgw.FileRequest
	2, // 6: lspgw.LspGateway.Health:input_type -> lspgw.ProjectRequest
	3, // 7: lspgw.LspGateway.DaemonStatus:input_type -> lspgw.DaemonStatusRequest
	4, // 8: lspgw.LspGateway.Shutdown:input_type -> lspgw.ShutdownRequest
	5, // 9: lspgw.LspGateway.GetDefinition:output_type -> lspgw.QueryResponse
	5, // 10: lspgw.LspGateway.GetReferences:output_type -> lspgw.QueryResponse
	5, // 11: lspgw.LspGateway.GetHover:output_type -> lspgw.QueryResponse
	5, // 12: lspgw.LspGateway.GetDocumentSymbols:output_type -> lspgw.QueryResponse
	5, // 13: lspgw.LspGateway.GetDiagnostics:output_type -> lspgw.QueryResponse
	5, // 14: lspgw.LspGateway.Health:output_type -> lspgw.QueryResponse
	5, // 15: lspgw.LspGateway.DaemonStatus:output_type -> lspgw.QueryResponse
	5, // 16: lspgw.LspGateway.Shutdown:output_type -> lspgw.QueryResponse
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lspgw_proto_init() }
func file_proto_lspgw_proto_init() {
	if File_proto_lspgw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lspgw_proto_rawDesc), len(file_proto_lspgw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lspgw_proto_goTypes,
		DependencyIndexes: file_proto_lspgw_proto_depIdxs,
		MessageInfos:      file_proto_lspgw_proto_msgTypes,
	}.Build()
	File_proto_lspgw_proto = out.File
	file_proto_lspgw_proto_goTypes = nil
	file_proto_lspgw_proto_depIdxs = nil
}
