[settings]
experimental = true
auto_install = true
lockfile = true

trusted_config_paths = [
  '~/.config/mise/mise.toml',
  '~/.dotfiles/config/mise/mise.toml',
]

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[tools]
# LLM
"npm:@openai/codex" = "latest"

# mcp / tools for llm
"npm:@upstash/context7-mcp" = "latest"

# zenn
"npm:zenn-cli" = "latest"

"pipx:apm-cli" = "latest"

"ruff" = "latest"

# Helm
"aqua:helm/chart-releaser" = "latest"
"aqua:helm/chart-testing" = "latest"

# Tree-sitter
"cargo:tree-sitter-cli" = "latest"

# Go Development
"go:golang.org/dl/gotip" = { version = "latest", install_env = { CGO_ENABLED = "0" } }
"go:github.com/nametake/golangci-lint-langserver" = { version = "latest", install_env = { CGO_ENABLED = "0" } }
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = { version = "latest", install_env = { CGO_ENABLED = "0" } }
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = { version = "latest", install_env = { CGO_ENABLED = "0" } }

"go:github.com/chrishrb/go-grip" = { version = "latest", install_env = { CGO_ENABLED = "0" } }
"go:github.com/mattn/memo" = { version = "latest", install_env = { CGO_ENABLED = "0" } }

# Own rapidly-evolving prototypes
"go:github.com/ngicks/crabswarm/cmd/crabswarm" = { version = "latest", install_env = { CGO_ENABLED = "0" } }
"go:github.com/ngicks/cmdman/cmd/cmdman" = { version = "latest", install_env = { CGO_ENABLED = "0" } }

[shell_alias]
golangci-lint-v1 = "mise exec 'go:github.com/golangci/golangci-lint/cmd/golangci-lint' -- golangci-lint "
golangci-lint-v2 = "mise exec 'go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint' -- golangci-lint "

[env]

[alias]
