[settings]
experimental = true
auto_install = true
idiomatic_version_file_enable_tools = ['node', 'python', 'rust']
lockfile = true

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[tools]
# core
deno = "latest"
node = "lts"
uv = "latest"
python = "latest"
ruby = "latest"
rust = { version = "stable" }
go = "latest"

# tools
"github:neovim/neovim" = "latest"
"gh" = "latest"
"glab" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest" # lazygit: opinionated git TUI
"go:github.com/junegunn/fzf" = "latest"          # fzf: fuzzy finder
"cargo:yazi-fm" = "latest"                       # yazi: file manager
"cargo:yazi-cli" = "latest"                      # ya: yazi CLI companion
"cargo:zellij" = "latest"                        # zellij: terminal multiplexer, tmux alternative
## better XX
"cargo:ripgrep" = "latest"   # rg: fast grep
"cargo:bat" = "latest"       # bat: better cat
"cargo:exa" = "latest"       # exa: better ls
"cargo:fd-find" = "latest"   # fd: better find
"cargo:bottom" = "latest"    # btm: system monitor
"cargo:du-dust" = "latest"   # dust: disk usage
"cargo:procs" = "latest"     # better ps
"cargo:sd" = "latest"        # sd: better sed
"cargo:hyperfine" = "latest" # hyperfine: benchmarking tool
## automation
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"
## k8s
"aqua:kubernetes/kompose" = "latest"
"aqua:kubernetes/kops" = "latest"
"aqua:kubernetes/kubernetes/kubectl" = "latest"
"aqua:kubernetes/kubernetes/kubectl-convert" = "latest"
## helm
"aqua:helm/helm" = "latest"
"aqua:helm/chart-releaser" = "latest"
"aqua:helm/chart-testing" = "latest"

# protobuf
"go:github.com/bufbuild/buf/cmd/buf" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" = "latest"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2" = "latest"
"npm:@bufbuild/protoc-gen-es" = "latest"

# LLM related
## cli anget
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
## custom slash
"pipx:github/spec-kit" = "latest"
## MCP
"npm:@upstash/context7-mcp" = "latest"
"pipx:oraios/serena" = "latest"

# go
## ls
"go:golang.org/x/tools/gopls" = "latest"
## formater
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
## linter
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
## debugger
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
## generators
"go:github.com/cweill/gotests/gotests" = "latest"
"go:github.com/haya14busa/goplay/cmd/goplay" = "latest"

[env]

[alias]
