[settings]
experimental = true
auto_install = true
idiomatic_version_file_enable_tools = ['node', 'python', 'rust']

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[tools]
# core
deno = "latest"
node = "lts"
uv = "latest"
python = "latest"
ruby = "latest"
rust = { version = "stable" }
go = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@upstash/context7-mcp" = "latest"

"pipx:oraios/serena" = { version = "latest" }

"go:github.com/jesseduffield/lazygit" = { version = "latest" }
"go:github.com/junegunn/fzf" = { version = "latest" }
"go:golang.org/x/tools/gopls" = { version = "latest" }
"go:golang.org/x/tools/cmd/goimports" = { version = "latest" }
"go:mvdan.cc/gofumpt" = { version = "latest" }
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = { version = "latest" }
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = { version = "latest" }
"go:github.com/go-delve/delve/cmd/dlv" = { version = "latest" }

"cargo:yazi-fm" = "latest"   # yazi file manager
"cargo:yazi-cli" = "latest"  # yazi CLI companion
"cargo:ripgrep" = "latest"   # rg - fast grep
"cargo:zellij" = "latest"    # terminal multiplexer
"cargo:bat" = "latest"       # better cat
"cargo:exa" = "latest"       # better ls
"cargo:fd-find" = "latest"   # better find
"cargo:zoxide" = "latest"    # better cd
"cargo:starship" = "latest"  # prompt
"cargo:bottom" = "latest"    # system monitor (btm)
"cargo:du-dust" = "latest"   # disk usage
"cargo:procs" = "latest"     # better ps
"cargo:sd" = "latest"        # better sed
"cargo:hyperfine" = "latest" # benchmarking tool
"cargo:tokei" = "latest"     # code statistics
"cargo:git-delta" = "latest" # better git diff

"github:neovim/neovim" = "latest"

[env]

[alias]
